logging:
    level:
        org:
            springframework:
                security: warn
        com:
            alibaba:
                nacos: info
    file:
        path: ../logs/${spring.application.name}
